name: flamby
channels:
  - conda
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pytest
  - ipython
  - pip:
    - large-image-source-openslide --find-links https://girder.github.io/large_image_wheels