common_args:
  training_type: "simulation"
  using_mlops: false
  random_seed: 0

data_args:
  dataset: "Fed-Heart-Disease"
  data_cache_dir: ""
  partition_method: "hetero"
  partition_alpha: 0.5
  debug: false # change here! flamby: debug or not
  preprocessed: false


model_args:
  model: "lr"

train_args:
  federated_optimizer: "FedAvg"
  client_id_list: "[]"
  client_num_in_total: 1000
  client_num_per_round: 4
  comm_round: 10
  epochs: 1
  batch_size: 10
  client_optimizer: sgd
  learning_rate: 0.01
  weight_decay: 0.0

validation_args:
  frequency_of_the_test: 5

device_args:
  worker_num: 4
  using_gpu: false
  gpu_mapping_file: gpu_mapping.yaml
  gpu_mapping_key: mapping_default

comm_args:
  backend: "MPI"
  is_mobile: 0


tracking_args:
  log_file_dir: ./log
  enable_wandb: false
  wandb_key: wandbkey
  wandb_project: fedml
  wandb_name: flamby_fed_heart_disease_fedml