# This is a basic workflow to help you get started with Actions
name: linting-validation

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Install dependencies
        run: pip install isort black==22.3.0
             pip install flake8

      - name: Run black
        run: black --line-length=89 --check .


      - name: Run FLAKE8
        run: flake8 --max-line-length=89 --per-file-ignores="*/__init__.py:F401" ./flamby

      - name: Run isort
        run: isort .
